development:
  adapter: postgresql
  encoding: unicode
  database: visa_development
  pool: 5
  username: rafael
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: visa_test
  pool: 5
  username: Rafael
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tpavc_production
  pool: 5
  username: deploy
  password: Reza2thetop
